export const LSKey = {
  Auth: 'auth',
  Blacklist: 'blacklist',
  Draft: 'draft',
  Favored: 'favored',
  ReadPosition: 'read-position',
  Notified: 'notified',
  SearchHistoryWeb: 'search-history-web',
  SearchHistoryWenku: 'search-history-wenku',
  SearchHistoryForum: 'search-history-forum',
  ForumSearchSetting: 'forum-search-setting',
  Setting: 'setting',
  SettingReader: 'setting-reader',
  WorkspaceGpt: 'workspace-gpt',
  WorkspaceSakura: 'workspace-sakura',
  WorkspaceGptPipeline: 'workspace-gpt-pipeline',
} as const;
